name: 'spring-boot-microservices-course'
services:
  catalog-service:
    image: 1234user1234/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=root1234
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - catalog-db

    deploy:
      resources:
        limits:
          memory: 800m