name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - 'main'
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/bookstore-catalog-service
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'openjdk'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle and Create Docker Image
        run: |
          cd catalog-service
          ./gradlew bootBuildImage --imageName=$DOCKER_IMAGE_NAME
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Push Docker Image
        run: |
          ./gradlew bootBuildImage --no-build-cache -x test
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-catalog-service
